### ISSUE TITLE
How can I resolve this weird error?

### ISSUE THREAD

**Issue by stevekwokdev** [hCaptcha/vue-hcaptcha#10]
Got this error after importing the package

 in ./node_modules/@hcaptcha/vue-hcaptcha/src/component/vue-hcaptcha.vue

Module build failed: ReferenceError: Unknown plugin "@babel/plugin-transform-modules-commonjs" specified in "C:\\Users\\admin\\Desktop\\vueweb\\client\\node_modules\\@hcaptcha\\vue-hcaptcha\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\admin\\Desktop\\vueweb\\client\\node_modules\\@hcaptcha\\vue-hcaptcha"
    at C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17       
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\file\index.js:212:65)     
    at new File (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-core\lib\transformation\pipeline.js:46:16)      
    at transpile (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\admin\Desktop\vueweb\client\node_modules\babel-loader\lib\index.js:173:20)

 @ ./node_modules/@hcaptcha/vue-hcaptcha/src/component/vue-hcaptcha.vue 4:0-105 5:0-118
 @ ./node_modules/@hcaptcha/vue-hcaptcha/src/main.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Register.vue     
 @ ./src/components/Register.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:80 webpack/hot/dev-server ./src/main.js

**Comment by anniestudent** [comment]
+1
